name: Deploy Ambiente X
env:
  APPLICATIONS: ${{github.event.client_payload.command}}
  APP_i365: "i365"
on:
  repository_dispatch:
    types: [run-jira-deploy]
jobs:
  setting-data:
    runs-on: ubuntu-20.04
    steps:
      - name: Obteniendo instrucciones
        run: |
          STR_APPS=$(echo $APPLICATIONS | sed 's/,//g')
          for i in $STR_APPS
          do
            if [ $i == "i365" ]
            then
              echo "APP_i365=i365" >> "$GITHUB_ENV"
            fi
          done
  call-workflow-i365:
    if: github.env.APP_i365 == 'i365'
    uses: mapuga/example-event-dispatcher-workflows/.github/workflows/ping.yml@master

