name: Deploy Ambiente X
on:
  repository_dispatch:
    types: [run-jira-deploy]
env:
  APPLICATIONS: ${{github.event.client_payload.command}}
  APP_i365: ""
  APP_API: ""
  APP_SABE2: ""
  APP_SABE3: ""
  DATABASE: ""
jobs:
  deploy-qa:
    runs-on: ubuntu-20.04
    steps:
      - name: Obteniendo datos QA
        run: |
          STR_APPS=$(echo $APPLICATIONS | sed 's/,//g')
          for i in $STR_APPS
          do
            if[ $i == "i365" ]
            then
              echo "detecto i365"
            fi
          done
  call-workflow-1-in-local-repo:
    if: github.event.client_payload.command == 'ping'
    uses: mapuga/example-event-dispatcher-workflows/.github/workflows/ping.yml@master

