name: Deploy Ambiente X
on:
  repository_dispatch:
    types: [run-jira-deploy]
env:
  APPLICATIONS: ${{github.event.client_payload.command}}
jobs:
  setting-data:
    runs-on: ubuntu-20.04
    outputs:
      appi365: ${{ steps.ambientes.outputs.appi365 }}
      database: ${{ steps.ambientes.outputs.database }}
    steps:
      - name: Obteniendo instrucciones
        id: ambientes
        run: |
          STR_APPS=$(echo $APPLICATIONS | sed 's/,//g')
          for i in $STR_APPS
          do
            if [ $i == "i365" ]
            then
              echo "appi365=i365" >> $GITHUB_OUTPUT
            fi
            if [ $i == "DB" ]
            then
              echo "database=DB" >> $GITHUB_OUTPUT
            fi
          done
  call-workflow-i365:
    needs: [setting-data]
    if: ${{ needs.setting-data.outputs.database == 'database' }} 
    uses: mapuga/example-event-dispatcher-workflows/.github/workflows/ping.yml@master

