name: Deploy Ambiente X
on:
  repository_dispatch:
    types: [run-jira-deploy]
jobs:
  deploy-qa:
    runs-on: ubuntu-20.04
    steps:
      - name: Obteniendo datos
        run: |
          echo "$GITHUB_REF_NAME will serve the internal behavior of GitHub Action"
