name: Deploy Ambiente X
on:
  repository_dispatch:
    types: [run-jira-deploy]
jobs:
  deploy-qa:
    runs-on: ubuntu-20.04
    steps:
      - name: Obteniendo datos QA
        run: |
          if [[ "${GITHUB_REF_NAME}" = "master" ]];
          then
            echo running on branch ${GITHUB_REF_NAME}
            echo el comando es ${{ github.event.client_payload.command }}
          else
            echo No esta en la rama QA
          fi
  call-workflow-database:
    if: github.event.client_payload.command == 'ping'
    uses: mapuga/example-event-dispatcher-workflows/.github/workflows/ping.yml@master
    if: github.event.client_payload.command == 'pong'
    uses: mapuga/example-event-dispatcher-workflows/.github/workflows/pong.yml@master
