name: Deploy Ambiente X
on:
  repository_dispatch:
    types: [run-jira-deploy]
jobs:
  deploy-qa:
    runs-on: ubuntu-20.04
    steps:
      - name: Obteniendo datos
        env:
          BRANCH: ${{env.GITHUB_REF_NAME}}
        run: |
          echo "$BRANCH"
