name: Deploy Ambiente X
env:
    RAMA_ACTUAL: ${{ env.GITHUB_REF_NAME }}
on:
  repository_dispatch:
    types: [run-jira-deploy]
jobs:
  deploy-qa:
    runs-on: ubuntu-20.04
    steps:
      - name: Obteniendo datos
        run: |
          echo "$RAMA_ACTUAL will serve the behavior of the GitHub Slug action"
